import { parseAtsPolicy } from "./parse.js";
import type { AtsEnginePolicy } from "./schema.js";

/**
 * A minimal, generic policy so the package is usable and testable on its own.
 *
 * Deliberately not the shipped one. The curated taxonomy — the real rule weights, thresholds,
 * synonym and implication maps, and the buzzword list — is private, and copying any of it here
 * would leak it into a package whose whole point is that it can eventually be published. What is
 * here is the smallest policy that exercises every rule kind and every vocabulary the parser
 * reads, so a consumer can score something the moment they install the package and a test can
 * run without a fixture.
 *
 * Everything language-bound lives in this data — month names, degree spellings, section
 * headings, title and school words, stopwords, action verbs. None of it is hardcoded in the
 * engine's source, which is what keeps adding a locale a matter of writing another policy rather
 * than editing the scorer.
 */
const DEFAULT_POLICY_JSON = {
  version: "ats-v2",
  rules: [
    {
      id: "ats-v2.parse.text",
      category: "parse",
      severity: "error",
      kind: "min-words",
      min: 50,
      weight: 20,
      passEvidence: "Recovered {n} words of text.",
      failEvidence: "Only {n} words of text could be recovered.",
      fix: "Save the resume as a text-based PDF rather than a scan or an image.",
    },
    {
      id: "ats-v2.contact.email",
      category: "contact",
      severity: "error",
      kind: "presence",
      pattern: String.raw`\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b`,
      flags: "i",
      scope: "document",
      weight: 12,
      passEvidence: "An email address was found.",
      failEvidence: "No email address was found.",
      fix: "Add an email address to the header of the resume.",
    },
    {
      id: "ats-v2.contact.position",
      category: "contact",
      severity: "warning",
      kind: "position",
      emailPattern: String.raw`\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b`,
      phonePattern: String.raw`(?:\+\d{1,3}[\s.-]?)?(?:\(?\d{3}\)?[\s.-]?)\d{3}[\s.-]?\d{4}`,
      windowFraction: 0.25,
      weight: 6,
      passEvidence: "Contact details appear near the top of the document.",
      failEvidence: "Contact details appear well below the top of the document.",
      fix: "Move the email address and phone number into the header.",
    },
    {
      id: "ats-v2.structure.experience",
      category: "structure",
      severity: "error",
      kind: "presence",
      pattern: String.raw`^(?:work\s+)?(?:experience|employment|history)`,
      flags: "i",
      scope: "heading",
      weight: 12,
      passEvidence: "An experience section heading was found.",
      failEvidence: "No experience section heading was found.",
      fix: "Add a heading reading 'Experience' above the work history.",
    },
    {
      id: "ats-v2.structure.education",
      category: "structure",
      severity: "warning",
      kind: "presence",
      pattern: String.raw`^education`,
      flags: "i",
      scope: "heading",
      weight: 8,
      passEvidence: "An education section heading was found.",
      failEvidence: "No education section heading was found.",
      fix: "Add a heading reading 'Education' above the qualifications.",
    },
    {
      id: "ats-v2.structure.skills",
      category: "structure",
      severity: "warning",
      kind: "presence",
      pattern: String.raw`^skills`,
      flags: "i",
      scope: "heading",
      weight: 8,
      passEvidence: "A skills section heading was found.",
      failEvidence: "No skills section heading was found.",
      fix: "Add a heading reading 'Skills' above the skills list.",
    },
    {
      id: "ats-v2.format.length",
      category: "format",
      severity: "warning",
      kind: "bands",
      metric: "wordCount",
      bands: [
        { upTo: 200, weight: 10 },
        { upTo: 1200, weight: 0 },
        { upTo: null, weight: 8 },
      ],
      passEvidence: "The resume is {n} words, a reasonable length.",
      failEvidence: "The resume is {n} words, outside the range most reviewers expect.",
      fix: "Aim for roughly one page per five years of experience.",
    },
    {
      id: "ats-v2.content.metrics",
      category: "content",
      severity: "warning",
      kind: "bands",
      metric: "metricsRatio",
      pattern: String.raw`\d`,
      flags: "i",
      bands: [
        { upTo: 0.15, weight: 10 },
        { upTo: null, weight: 0 },
      ],
      passEvidence: "{pct}% of content lines carry a number.",
      failEvidence: "Only {pct}% of content lines carry a number.",
      fix: "Quantify outcomes: amounts, percentages, timeframes, headcounts.",
    },
    {
      id: "ats-v2.content.verbs",
      category: "content",
      severity: "warning",
      kind: "bands",
      metric: "actionVerbRatio",
      pattern: String.raw`\b(?:led|built|designed|delivered|improved|reduced|increased|created|launched|managed|developed|automated|scaled|migrated|owned)`,
      flags: "i",
      bands: [
        { upTo: 0.2, weight: 8 },
        { upTo: null, weight: 0 },
      ],
      passEvidence: "{pct}% of content lines open with an action verb.",
      failEvidence: "Only {pct}% of content lines open with an action verb.",
      fix: "Start each bullet with a verb describing what you did.",
    },
    {
      id: "ats-v2.content.buzzwords",
      category: "content",
      severity: "info",
      kind: "bands",
      metric: "buzzwordCount",
      bands: [
        { upTo: 2, weight: 0 },
        { upTo: null, weight: 5 },
      ],
      passEvidence: "Little filler language.",
      failEvidence: "{n} filler phrases were found.",
      fix: "Replace filler phrases with a specific thing you did.",
    },
    {
      id: "ats-v2.format.columns",
      category: "format",
      severity: "error",
      kind: "layout",
      metric: "columnRatio",
      appliesWhen: "layout",
      bands: [
        { upTo: 0.15, weight: 0 },
        { upTo: null, weight: 15 },
      ],
      passEvidence: "The document reads as a single column.",
      failEvidence: "The document appears to use a multi-column layout.",
      fix: "Use a single-column layout; columns extract in a scrambled order.",
    },
    {
      id: "ats-v2.format.tables",
      category: "format",
      severity: "warning",
      kind: "layout",
      metric: "tableCount",
      appliesWhen: "layout",
      bands: [
        { upTo: 0, weight: 0 },
        { upTo: null, weight: 10 },
      ],
      passEvidence: "No ruled tables were found.",
      failEvidence: "{n} ruled tables were found.",
      fix: "Replace tables with plain paragraphs and bullets.",
    },
    {
      id: "ats-v2.parse.roles",
      category: "parse",
      severity: "error",
      kind: "parsed",
      metric: "rolesDetected",
      bands: [
        { upTo: 0, weight: 15 },
        { upTo: null, weight: 0 },
      ],
      passEvidence: "{n} roles were recovered from the work history.",
      failEvidence: "No roles could be recovered from the work history.",
      fix: "Give each job a line with the title, the employer, and a date range.",
    },
    {
      id: "ats-v2.parse.roleCompleteness",
      category: "parse",
      severity: "warning",
      kind: "parsed",
      metric: "roleCompleteness",
      bands: [
        { upTo: 0.6, weight: 10 },
        { upTo: null, weight: 0 },
      ],
      passEvidence: "{pct}% of recovered roles have a title, an employer and a start date.",
      failEvidence: "Only {pct}% of recovered roles are complete.",
      fix: "Make sure every job lists a title, an employer, and a date range.",
    },
    {
      id: "ats-v2.parse.contact",
      category: "parse",
      severity: "warning",
      kind: "parsed",
      metric: "contactCompleteness",
      bands: [
        { upTo: 0.66, weight: 8 },
        { upTo: null, weight: 0 },
      ],
      passEvidence: "{pct}% of the expected contact fields were recovered.",
      failEvidence: "Only {pct}% of the expected contact fields were recovered.",
      fix: "Include a name, an email address, and a phone number as plain text.",
    },
  ],
  keywordMatch: {
    // Round, obviously-illustrative numbers. They encode only the ordering the engine needs — a
    // stated requirement outranks the body, which outranks a nice-to-have, and ordinary English is
    // discounted against a recognised skill. The *tuned* values are calibration and stay private;
    // anything here that happened to match them would be shipping the moat in the demo.
    requiredWeight: 2,
    preferredWeight: 0.5,
    responsibilitiesWeight: 0.5,
    defaultWeight: 1,
    generalTermWeight: 0.25,
    sections: {
      required: String.raw`^(?:requirements|qualifications|what\s+you.{0,3}ll\s+need|must\s+have)`,
      preferred: String.raw`^(?:nice\s+to\s+have|preferred|bonus|desirable|plus)`,
      responsibilities: String.raw`^(?:responsibilities|what\s+you.{0,3}ll\s+do|the\s+role|about\s+the\s+role)`,
      excluded: String.raw`^(?:about\s+us|benefits|perks|equal\s+opportunity|our\s+values|why\s+join)`,
    },
    stopwords: [
      "the",
      "and",
      "for",
      "with",
      "you",
      "your",
      "our",
      "are",
      "will",
      "have",
      "this",
      "that",
      "from",
      "they",
      "them",
      "who",
      "was",
      "were",
      "been",
      "has",
      "had",
      "not",
      "but",
      "all",
      "can",
      "any",
      "may",
      "more",
      "most",
      "other",
      "some",
      "such",
      "than",
      "then",
      "there",
      "these",
      "those",
      "into",
      "over",
      "also",
      "about",
      "work",
      "working",
      "team",
      "teams",
      "role",
      "years",
      "year",
      "experience",
      "strong",
      "good",
      "great",
      "excellent",
      "ability",
      "skills",
      "knowledge",
      "understanding",
      "familiarity",
      "proficiency",
      "including",
      "etc",
      "new",
      "well",
      "help",
      "join",
      "looking",
      "candidate",
      "candidates",
      "opportunity",
      "company",
      "business",
      "across",
      "within",
      "using",
      "use",
      "like",
      "make",
      "need",
      "needs",
      "want",
      "plus",
      "must",
    ],
    synonyms: {
      js: "javascript",
      ts: "typescript",
      k8s: "kubernetes",
      postgres: "postgresql",
      psql: "postgresql",
      golang: "go",
      py: "python",
      iac: "infrastructure as code",
      ci: "ci/cd",
      cd: "ci/cd",
    },
    implies: {
      terraform: ["infrastructure as code"],
      kubernetes: ["containers"],
      docker: ["containers"],
      postgresql: ["relational database", "sql"],
      mysql: ["relational database", "sql"],
      react: ["javascript"],
      typescript: ["javascript"],
    },
    phrases: [
      "infrastructure as code",
      "relational database",
      "machine learning",
      "continuous integration",
      "continuous delivery",
      "distributed systems",
      "event streaming",
      "unit testing",
      "code review",
      "ci/cd",
      "documentation",
      "containers",
      "sql",
    ],
    buzzwords: [
      "team player",
      "hard worker",
      "hardworking",
      "self-starter",
      "results-driven",
      "go-getter",
      "think outside the box",
      "synergy",
      "detail oriented",
      "detail-oriented",
    ],
  },
  text: {
    contentLineVerbs: [
      "managed",
      "led",
      "built",
      "developed",
      "designed",
      "improved",
      "reduced",
      "increased",
      "delivered",
      "achieved",
      "created",
      "generated",
      "optimized",
      "launched",
      "spearheaded",
      "engineered",
      "maintained",
      "scaled",
      "automated",
    ],
  },
  resumeParse: {
    sections: {
      experience: String.raw`^(?:work\s+)?(?:experience|employment|history|professional\s+experience)`,
      education: String.raw`^education`,
      skills: String.raw`^(?:skills|technical\s+skills|technologies)`,
      projects: String.raw`^projects`,
      other: String.raw`^(?:summary|objective|profile|certifications?|awards?|publications?|languages|interests|volunteering|references)`,
    },
    months: {
      jan: 1,
      feb: 2,
      mar: 3,
      apr: 4,
      may: 5,
      jun: 6,
      jul: 7,
      aug: 8,
      sep: 9,
      sept: 9,
      oct: 10,
      nov: 11,
      dec: 12,
    },
    openEnded: ["present", "current", "now", "ongoing", "to date", "till date"],
    titleWords: [
      "engineer",
      "developer",
      "manager",
      "director",
      "designer",
      "analyst",
      "architect",
      "consultant",
      "lead",
      "head",
      "officer",
      "scientist",
      "specialist",
      "administrator",
      "intern",
      "president",
      "founder",
      "coordinator",
      "supervisor",
      "associate",
      "assistant",
      "technician",
    ],
    schoolWords: [
      "university",
      "college",
      "institute",
      "school",
      "academy",
      "polytechnic",
      "seminary",
    ],
    degrees: {
      diploma: String.raw`(?:\b|^)(diploma|certificate)(?![a-z])`,
      associate: String.raw`(?:\b|^)(associate(?:'?s)?(?:\s+degree)?|a\.?a\.?s?\.?)(?![a-z])`,
      bachelor: String.raw`(?:\b|^)(bachelor(?:'?s)?(?:\s+of\s+[a-z]+)?|b\.?s\.?c?\.?|b\.?a\.?|b\.?eng\.?|b\.?tech\.?)(?![a-z])`,
      master: String.raw`(?:\b|^)(master(?:'?s)?(?:\s+of\s+[a-z]+)?|m\.?s\.?c?\.?|m\.?a\.?|m\.?eng\.?|m\.?b\.?a\.?)(?![a-z])`,
      doctorate: String.raw`(?:\b|^)(doctorate|ph\.?d\.?|d\.?phil\.?)(?![a-z])`,
    },
  },
};

/**
 * Validated at module load, so a mistake in the default is caught by this package's own build
 * and test run rather than becoming a confusing schema error inside somebody else's application.
 *
 * Measured before choosing this: the parse costs about 5ms once, against ~35ms to import the
 * module graph at all (mostly zod). Deferring it behind a lazy proxy was tried and reverted —
 * it saved that 5ms but put a trap on every property read of an object the engine also uses as
 * a `WeakMap` key, which is a lot of subtlety to buy back a rounding error. A consumer who never
 * imports `DEFAULT_POLICY` pays nothing either way: the package sets `sideEffects: false`, so
 * this module tree-shakes out entirely.
 */
export const DEFAULT_POLICY: AtsEnginePolicy = parseAtsPolicy(DEFAULT_POLICY_JSON);
