import { describe, expect, it } from "vitest";

import { reportToPlainText } from "@/features/ats-checker/services";
import { scoreTone, sortByCategoryOrder } from "@/features/ats-checker/data";
import type { AtsFullReport } from "@/features/ats-checker/types";

function report(overrides: Partial<AtsFullReport> = {}): AtsFullReport {
  return {
    version: "ats-v2",
    restricted: false,
    verdict: "needs-work",
    readinessScore: 74,
    jobMatchScore: 61,

    matchedKeywords: ["react", "typescript"],
    missingKeywords: ["kubernetes"],
    parsingWarnings: [],
    strengths: ["Contact details sit in the top 30%"],

    failedChecks: [
      {
        id: "ats-v2.content.metrics",
        category: "content",
        severity: "warning",
        passed: false,
        evidence: "2 of 14 bullets carry a number",
        scoreImpact: 10,
        fix: "Quantify more bullets.",
      },
      {
        id: "ats-v2.structure.skills",
        category: "structure",
        severity: "error",
        passed: false,
        evidence: "No skills section found",
        scoreImpact: 6,
        fix: "Add a labelled Skills section.",
      },
    ],

    prioritizedFixes: ["Quantify more bullets.", "Add a labelled Skills section."],

    rules: [],

    categories: [
      { category: "content", score: 48, passed: 1, total: 3, lost: 10, possible: 20 },
      { category: "parse", score: 100, passed: 2, total: 2, lost: 0, possible: 20 },
    ],

    checksPassed: 9,
    checksTotal: 11,
    wordCount: 612,
    ...overrides,
  };
}

describe("ATS report as clipboard text", () => {
  it("orders fixes by points recovered, not by the order the rules ran", () => {
    const text = reportToPlainText(report(), "https://veriworkly.com");

    expect(text).toContain("1. Quantify more bullets.");
    expect(text).toContain("2. Add a labelled Skills section.");
    expect(text.indexOf("Quantify more bullets.")).toBeLessThan(
      text.indexOf("Add a labelled Skills section."),
    );
  });

  it("carries the evidence and the points beside each fix", () => {
    const text = reportToPlainText(report(), "https://veriworkly.com");

    expect(text).toContain("Why: 2 of 14 bullets carry a number");
    expect(text).toContain("Worth: 10 points");
  });

  it("labels an unscored job match instead of printing null", () => {
    const text = reportToPlainText(report({ jobMatchScore: null }), "https://veriworkly.com");

    expect(text).toContain("Job match: not scored (no job description provided)");
    expect(text).not.toContain("null");
    // With no job description there are no keyword lists to report either.
    expect(text).not.toContain("KEYWORDS");
  });

  it("says 'none' rather than leaving an empty keyword line dangling", () => {
    const text = reportToPlainText(
      report({ matchedKeywords: [], missingKeywords: [] }),
      "https://veriworkly.com",
    );

    expect(text).toContain("Matched: none");
    expect(text).toContain("Missing: none");
  });

  it("omits sections that have nothing in them", () => {
    const text = reportToPlainText(
      report({ failedChecks: [], strengths: [] }),
      "https://veriworkly.com",
    );

    expect(text).not.toContain("FIX THESE FIRST");
    expect(text).not.toContain("ALREADY WORKING");
  });

  it("attributes the report to the checker URL", () => {
    expect(reportToPlainText(report(), "https://veriworkly.com")).toContain(
      "Generated by https://veriworkly.com/ats-checker",
    );
  });
});

describe("ATS category presentation helpers", () => {
  it("presents areas in pipeline order regardless of the order the engine sent them", () => {
    const ordered = sortByCategoryOrder([
      { category: "format" },
      { category: "contact" },
      { category: "parse" },
    ]);

    expect(ordered.map((entry) => entry.category)).toEqual(["parse", "contact", "format"]);
  });

  it("puts an unrecognised category last instead of dropping it", () => {
    const ordered = sortByCategoryOrder([{ category: "brand-new" }, { category: "parse" }]);

    expect(ordered.map((entry) => entry.category)).toEqual(["parse", "brand-new"]);
  });

  it("bands scores on the same thresholds the gauge and the bars share", () => {
    expect(scoreTone(80)).toBe("good");
    expect(scoreTone(79)).toBe("warn");
    expect(scoreTone(55)).toBe("warn");
    expect(scoreTone(54)).toBe("bad");
  });
});
