/** The community policy's job-matching vocabulary and weights. */
export const DEFAULT_KEYWORD_MATCH = {
  // Round, obviously-illustrative numbers. They encode only the ordering the engine needs — a
  // stated requirement outranks the body, which outranks a nice-to-have, and ordinary English is
  // discounted against a recognised skill. The *tuned* values are calibration and stay private;
  // anything here that happened to match them would be shipping the moat in the demo.
  requiredWeight: 2,
  preferredWeight: 0.5,
  responsibilitiesWeight: 0.5,
  defaultWeight: 1,
  generalTermWeight: 0.25,
  sections: {
    required: String.raw`^(?:requirements|qualifications|what\s+you.{0,3}ll\s+need|must\s+have)`,
    preferred: String.raw`^(?:nice\s+to\s+have|preferred|bonus|desirable|plus)`,
    responsibilities: String.raw`^(?:responsibilities|what\s+you.{0,3}ll\s+do|the\s+role|about\s+the\s+role)`,
    excluded: String.raw`^(?:about\s+us|benefits|perks|equal\s+opportunity|our\s+values|why\s+join)`,
  },
  stopwords: [
    "the",
    "and",
    "for",
    "with",
    "you",
    "your",
    "our",
    "are",
    "will",
    "have",
    "this",
    "that",
    "from",
    "they",
    "them",
    "who",
    "was",
    "were",
    "been",
    "has",
    "had",
    "not",
    "but",
    "all",
    "can",
    "any",
    "may",
    "more",
    "most",
    "other",
    "some",
    "such",
    "than",
    "then",
    "there",
    "these",
    "those",
    "into",
    "over",
    "also",
    "about",
    "work",
    "working",
    "team",
    "teams",
    "role",
    "years",
    "year",
    "experience",
    "strong",
    "good",
    "great",
    "excellent",
    "ability",
    "skills",
    "knowledge",
    "understanding",
    "familiarity",
    "proficiency",
    "including",
    "etc",
    "new",
    "well",
    "help",
    "join",
    "looking",
    "candidate",
    "candidates",
    "opportunity",
    "company",
    "business",
    "across",
    "within",
    "using",
    "use",
    "like",
    "make",
    "need",
    "needs",
    "want",
    "plus",
    "must",
    // Function words. Terms of one or two letters are already dropped unless they are a
    // named skill, but the longer ones and the posting filler below still reached the report.
    "a",
    "an",
    "as",
    "at",
    "be",
    "by",
    "in",
    "is",
    "it",
    "its",
    "of",
    "on",
    "or",
    "to",
    "we",
    "us",
    "via",
    "per",
    "deep",
    "hands",
    "hands-on",
    "prior",
    "exposure",
    "solid",
    "proven",
    "demonstrated",
    "preferred",
    "required",
    "ideally",
  ],
  synonyms: {
    js: "javascript",
    ts: "typescript",
    k8s: "kubernetes",
    postgres: "postgresql",
    psql: "postgresql",
    golang: "go",
    py: "python",
    iac: "infrastructure as code",
    ci: "ci/cd",
    cd: "ci/cd",
  },
  implies: {
    terraform: ["infrastructure as code"],
    kubernetes: ["containers"],
    docker: ["containers"],
    postgresql: ["relational database", "sql"],
    mysql: ["relational database", "sql"],
    react: ["javascript"],
    typescript: ["javascript"],
  },
  phrases: [
    "infrastructure as code",
    "relational database",
    "machine learning",
    "continuous integration",
    "continuous delivery",
    "distributed systems",
    "event streaming",
    "unit testing",
    "code review",
    "ci/cd",
    "documentation",
    "containers",
    "sql",
  ],
  buzzwords: [
    "team player",
    "hard worker",
    "hardworking",
    "self-starter",
    "results-driven",
    "go-getter",
    "think outside the box",
    "synergy",
    "detail oriented",
    "detail-oriented",
  ],
};
