/** The community policy's rules: what is checked, what it can cost, how to fix it. */
export const DEFAULT_RULES = [
  {
    id: "ats-v2.parse.text",
    category: "parse",
    severity: "error",
    kind: "min-words",
    min: 50,
    weight: 20,
    passEvidence: "Recovered {n} words of text.",
    failEvidence: "Only {n} words of text could be recovered.",
    fix: "Save the resume as a text-based PDF rather than a scan or an image.",
  },
  {
    id: "ats-v2.contact.email",
    category: "contact",
    severity: "error",
    kind: "presence",
    pattern: String.raw`(?<![A-Z0-9._%+-])[A-Z0-9._%+-]{1,64}@[A-Z0-9-]{1,63}(?:\.[A-Z0-9-]{1,63}){0,8}\.[A-Z]{2,24}\b`,
    flags: "i",
    scope: "document",
    weight: 12,
    passEvidence: "An email address was found.",
    failEvidence: "No email address was found.",
    fix: "Add an email address to the header of the resume.",
  },
  {
    id: "ats-v2.contact.position",
    category: "contact",
    severity: "warning",
    kind: "position",
    // No patterns: the rule locates the email and phone the parser recovered, so a phone number
    // in any country's format counts.
    windowFraction: 0.25,
    weight: 6,
    passEvidence: "Contact details appear near the top of the document.",
    failEvidence: "Contact details appear well below the top of the document.",
    fix: "Move the email address and phone number into the header.",
  },
  {
    id: "ats-v2.structure.experience",
    category: "structure",
    severity: "error",
    kind: "section",
    section: "experience",
    weight: 12,
    passEvidence: "An experience section heading was found.",
    failEvidence: "No experience section heading was found.",
    fix: "Add a heading reading 'Experience' above the work history.",
  },
  {
    id: "ats-v2.structure.education",
    category: "structure",
    severity: "warning",
    kind: "section",
    section: "education",
    weight: 8,
    passEvidence: "An education section heading was found.",
    failEvidence: "No education section heading was found.",
    fix: "Add a heading reading 'Education' above the qualifications.",
  },
  {
    id: "ats-v2.structure.skills",
    category: "structure",
    severity: "warning",
    kind: "section",
    section: "skills",
    weight: 8,
    passEvidence: "A skills section heading was found.",
    failEvidence: "No skills section heading was found.",
    fix: "Add a heading reading 'Skills' above the skills list.",
  },
  {
    id: "ats-v2.format.length",
    category: "format",
    severity: "warning",
    kind: "bands",
    metric: "wordCount",
    bands: [
      { upTo: 200, weight: 10 },
      { upTo: 1200, weight: 0 },
      { upTo: null, weight: 8 },
    ],
    passEvidence: "The resume is {n} words, a reasonable length.",
    failEvidence: "The resume is {n} words, outside the range most reviewers expect.",
    fix: "Aim for roughly one page per five years of experience.",
  },
  {
    id: "ats-v2.format.letterSpacing",
    category: "format",
    severity: "warning",
    kind: "bands",
    metric: "letterSpacedLines",
    bands: [
      { upTo: 0, weight: 0 },
      { upTo: null, weight: 8 },
    ],
    passEvidence: "Headings extract as whole words.",
    failEvidence:
      '{n} lines extract with a space between letters, as a heading set as "E X P E R I E N C E" does.',
    fix: "Remove the letter spacing (tracking) from section headings so they extract as words.",
  },
  {
    id: "ats-v2.content.metrics",
    category: "content",
    severity: "warning",
    kind: "bands",
    metric: "metricsRatio",
    // A number that is not a date. `\d` alone counted every "Jan 2020 - Present" header as a
    // quantified outcome, so a resume with no metrics at all still passed on its dates.
    pattern: String.raw`[$€£₹%]|(?<!\d)(?<!(?:19|20)\d{2}\s*[/.-]\s*)(?!(?:19|20)\d{2}(?!\d))(?!\d{1,2}\s*[/.-]\s*(?:19|20)\d{2}(?!\d))\d+`,
    flags: "i",
    bands: [
      { upTo: 0.15, weight: 10 },
      { upTo: null, weight: 0 },
    ],
    passEvidence: "{pct}% of content lines carry a number.",
    failEvidence: "Only {pct}% of content lines carry a number.",
    fix: "Quantify outcomes: amounts, percentages, timeframes, headcounts.",
  },
  {
    id: "ats-v2.content.verbs",
    category: "content",
    severity: "warning",
    kind: "bands",
    metric: "actionVerbRatio",
    // No pattern: the verbs are `text.actionVerbs`, which a language pack extends.
    flags: "i",
    bands: [
      { upTo: 0.2, weight: 8 },
      { upTo: null, weight: 0 },
    ],
    passEvidence: "{pct}% of content lines open with an action verb.",
    failEvidence: "Only {pct}% of content lines open with an action verb.",
    fix: "Start each bullet with a verb describing what you did.",
  },
  {
    id: "ats-v2.content.buzzwords",
    category: "content",
    severity: "info",
    kind: "bands",
    metric: "buzzwordCount",
    bands: [
      { upTo: 2, weight: 0 },
      { upTo: null, weight: 5 },
    ],
    passEvidence: "Little filler language.",
    failEvidence: "{n} filler phrases were found.",
    fix: "Replace filler phrases with a specific thing you did.",
  },
  {
    id: "ats-v2.format.columns",
    category: "format",
    severity: "error",
    kind: "layout",
    metric: "columnRatio",
    appliesWhen: "layout",
    bands: [
      { upTo: 0.15, weight: 0 },
      { upTo: null, weight: 15 },
    ],
    passEvidence: "The document reads as a single column.",
    failEvidence: "The document appears to use a multi-column layout.",
    fix: "Use a single-column layout; columns extract in a scrambled order.",
  },
  {
    id: "ats-v2.format.tables",
    category: "format",
    severity: "warning",
    kind: "layout",
    metric: "tableCount",
    appliesWhen: "layout",
    bands: [
      { upTo: 0, weight: 0 },
      { upTo: null, weight: 10 },
    ],
    passEvidence: "No ruled tables were found.",
    failEvidence: "{n} ruled tables were found.",
    fix: "Replace tables with plain paragraphs and bullets.",
  },
  {
    id: "ats-v2.content.timeline",
    category: "content",
    severity: "info",
    kind: "bands",
    metric: "timelineIssues",
    bands: [
      { upTo: 0, weight: 0 },
      { upTo: null, weight: 3 },
    ],
    passEvidence: "The dates in the work history are consistent.",
    failEvidence: "{n} dates in the work history look wrong: {sample}.",
    fix: "Check the dates: a role cannot start after today, and an end date left off makes jobs overlap.",
  },
  {
    // Light: a recruiter forgives "Git" with no bullet behind it. What it says is where the
    // resume could show its claims, which is what a per-requirement screener now looks for.
    id: "ats-v2.content.skillEvidence",
    category: "content",
    severity: "info",
    kind: "bands",
    metric: "unsupportedSkills",
    bands: [
      { upTo: 0.5, weight: 0 },
      { upTo: null, weight: 3 },
    ],
    passEvidence: "Most listed skills are backed by the work they were used in.",
    failEvidence: "{pct}% of listed skills appear nowhere but the skills list, such as {sample}.",
    fix: "Name each key skill in the role or project where you used it, not only in the list.",
  },
  {
    id: "ats-v2.parse.imageOnly",
    category: "parse",
    severity: "error",
    kind: "layout",
    metric: "imageOnlyPages",
    appliesWhen: "layout",
    bands: [
      { upTo: 0, weight: 0 },
      { upTo: null, weight: 15 },
    ],
    passEvidence: "Every page has a text layer.",
    failEvidence: "{n} pages are pictures with no text, so an ATS reads nothing on them.",
    fix: "Export the resume as a text PDF rather than scanning it or saving it as an image.",
  },
  // Integrity. Deductions in points (`penalty`), never part of the denominator: they say what
  // a resume does to game a screener, not how good it is, and an honest resume must score as
  // if they did not exist. Heaviest where recruiters reject outright when they find it.
  {
    id: "ats-v2.integrity.promptInjection",
    category: "integrity",
    severity: "error",
    kind: "bands",
    metric: "injectionPhrases",
    penalty: true,
    bands: [
      { upTo: 0, weight: 0 },
      { upTo: null, weight: 30 },
    ],
    passEvidence: "No instructions aimed at an AI screener.",
    failEvidence: 'An instruction aimed at an AI screener was found: "{sample}".',
    fix: "Remove it. Recruiters and screening tools treat instructions to an AI as manipulation, and many reject the application on sight.",
  },
  {
    id: "ats-v2.integrity.hiddenText",
    category: "integrity",
    severity: "error",
    kind: "layout",
    metric: "hiddenTextChars",
    appliesWhen: "layout",
    penalty: true,
    // A few stray characters (a white space glyph, a hairline label) are layout, not intent.
    bands: [
      { upTo: 20, weight: 0 },
      { upTo: null, weight: 30 },
    ],
    passEvidence: "No hidden text.",
    failEvidence:
      '{n} characters are hidden from a reader but read by an ATS, starting "{sample}".',
    fix: "Remove hidden text. White or tiny text and text behind an image is read by the ATS and treated as keyword stuffing once a recruiter sees it.",
  },
  {
    id: "ats-v2.integrity.copiedPosting",
    category: "integrity",
    severity: "error",
    kind: "bands",
    metric: "copiedPostingRatio",
    penalty: true,
    bands: [
      { upTo: 0.3, weight: 0 },
      { upTo: null, weight: 25 },
    ],
    passEvidence: "The resume is not a copy of the posting.",
    failEvidence:
      '{pct}% of the job posting appears word for word in the resume, such as "{sample}".',
    fix: "Describe your own experience. A pasted posting is caught the moment a recruiter reads the resume.",
  },
  {
    id: "ats-v2.integrity.invisibleCharacters",
    category: "integrity",
    severity: "warning",
    kind: "bands",
    metric: "invisibleCharacters",
    penalty: true,
    bands: [
      { upTo: 0, weight: 0 },
      { upTo: null, weight: 10 },
    ],
    passEvidence: "No invisible characters.",
    failEvidence: "{n} invisible characters were found in the text.",
    fix: "Remove zero-width and other invisible characters; retype any word they split.",
  },
  {
    id: "ats-v2.integrity.homoglyphs",
    category: "integrity",
    severity: "warning",
    kind: "bands",
    metric: "homoglyphWords",
    penalty: true,
    bands: [
      { upTo: 0, weight: 0 },
      { upTo: null, weight: 10 },
    ],
    passEvidence: "No look-alike letters from other alphabets.",
    failEvidence: '{n} words mix Latin with look-alike Cyrillic letters, such as "{sample}".',
    fix: "Retype those words: they look right but no search matches them.",
  },
  {
    id: "ats-v2.integrity.keywordStuffing",
    category: "integrity",
    severity: "warning",
    kind: "bands",
    metric: "stuffedTerms",
    penalty: true,
    bands: [
      { upTo: 0, weight: 0 },
      { upTo: null, weight: 10 },
    ],
    passEvidence: "No keyword stuffing.",
    failEvidence:
      '{n} terms or lines are repeated far beyond what the text needs, such as "{sample}".',
    fix: "Name each skill where you used it. Repetition does not raise a match score in a modern ATS, and recruiters read it as stuffing.",
  },
  {
    // Like the date of birth: convention, not parsing. An ATS reads past a photo, a recruiter
    // in the US or UK is told to discard a resume carrying one, and in Germany it is usual.
    // Light without a known country; the region packs turn it off or raise it.
    id: "ats-v2.format.photo",
    category: "format",
    severity: "info",
    kind: "layout",
    metric: "imageCount",
    appliesWhen: "layout",
    bands: [
      { upTo: 0, weight: 0 },
      { upTo: null, weight: 2 },
    ],
    passEvidence: "No photo was found.",
    failEvidence: "{n} images were found, most likely a photo.",
    fix: "Leave the photo off unless the country you are applying in expects one.",
  },
  {
    id: "ats-v2.parse.roles",
    category: "parse",
    severity: "error",
    kind: "parsed",
    metric: "rolesDetected",
    bands: [
      { upTo: 0, weight: 15 },
      { upTo: null, weight: 0 },
    ],
    passEvidence: "{n} roles were recovered from the work history.",
    failEvidence: "No roles could be recovered from the work history.",
    fix: "Give each job a line with the title, the employer, and a date range.",
  },
  {
    id: "ats-v2.parse.roleCompleteness",
    category: "parse",
    severity: "warning",
    kind: "parsed",
    metric: "roleCompleteness",
    bands: [
      { upTo: 0.6, weight: 10 },
      { upTo: null, weight: 0 },
    ],
    passEvidence: "{pct}% of recovered roles have a title, an employer and a start date.",
    failEvidence: "Only {pct}% of recovered roles are complete.",
    fix: "Make sure every job lists a title, an employer, and a date range.",
  },
  {
    id: "ats-v2.parse.contact",
    category: "parse",
    severity: "warning",
    kind: "parsed",
    metric: "contactCompleteness",
    bands: [
      { upTo: 0.66, weight: 8 },
      { upTo: null, weight: 0 },
    ],
    passEvidence: "{pct}% of the expected contact fields were recovered.",
    failEvidence: "Only {pct}% of the expected contact fields were recovered.",
    fix: "Include a name, an email address, and a phone number as plain text.",
  },
  {
    // Convention, not parsing: an ATS stores the date fine. Whether it belongs on the page
    // depends on the country — expected in much of Asia, optional in Germany, a liability in
    // the US, UK and Canada, where it invites age discrimination. Light here because the
    // country is unknown; the region packs set it to nothing or raise it.
    id: "ats-v2.privacy.dateOfBirth",
    category: "contact",
    severity: "info",
    kind: "parsed",
    metric: "dateOfBirthStated",
    bands: [
      { upTo: 0, weight: 0 },
      { upTo: null, weight: 2 },
    ],
    passEvidence: "No date of birth is stated.",
    failEvidence: "A date of birth is stated.",
    fix: "Leave your date of birth off unless the country you are applying in expects it.",
  },
];
