import { categoryMeta, sortByCategoryOrder } from "../data/categories";
import type { AtsFullReport, AtsRuleResult } from "../types";

export function reportToPlainText(
  report: AtsFullReport,
  siteUrl: string = "https://veriworkly.com",
): string {
  const lines: string[] = [];

  lines.push("========================================");
  lines.push("VERIWORKLY ATS RESUME READINESS REPORT");
  lines.push("========================================");
  lines.push("");
  lines.push(`ATS Readiness: ${report.readinessScore}/100`);

  if (report.jobMatchScore !== null) {
    lines.push(`Job Match: ${report.jobMatchScore}/100`);
  } else {
    lines.push("Job match: not scored (no job description provided)");
  }

  lines.push(`Verdict: ${report.verdict}`);
  lines.push("");

  if (report.categories.length > 0) {
    lines.push("----------------------------------------");
    lines.push("CATEGORY BREAKDOWN");
    lines.push("----------------------------------------");
    const sortedCategories = sortByCategoryOrder(report.categories);
    for (const cat of sortedCategories) {
      const meta = categoryMeta(cat.category);
      lines.push(`- ${meta.label}: ${cat.score}% (${cat.passed}/${cat.total} checks)`);
    }
    lines.push("");
  }

  if (report.failedChecks.length > 0) {
    lines.push("----------------------------------------");
    lines.push("FIX THESE FIRST");
    lines.push("----------------------------------------");

    // Sort by scoreImpact descending
    const sortedFixes = [...report.failedChecks].sort(
      (a: AtsRuleResult, b: AtsRuleResult) => b.scoreImpact - a.scoreImpact,
    );

    sortedFixes.forEach((check, index) => {
      lines.push(`${index + 1}. ${check.fix}`);
      lines.push(`   Why: ${check.evidence}`);
      lines.push(`   Worth: ${check.scoreImpact} points`);
    });
    lines.push("");
  }

  if (report.strengths.length > 0) {
    lines.push("----------------------------------------");
    lines.push("ALREADY WORKING");
    lines.push("----------------------------------------");
    for (const strength of report.strengths) {
      lines.push(`* ${strength}`);
    }
    lines.push("");
  }

  if (report.jobMatchScore !== null) {
    lines.push("----------------------------------------");
    lines.push("KEYWORDS");
    lines.push("----------------------------------------");

    const matched = report.matchedKeywords.length > 0 ? report.matchedKeywords.join(", ") : "none";
    lines.push(`Matched: ${matched}`);

    const missing = report.missingKeywords.length > 0 ? report.missingKeywords.join(", ") : "none";
    lines.push(`Missing: ${missing}`);
    lines.push("");
  }

  lines.push("========================================");
  lines.push(`Generated by ${siteUrl}/ats-checker`);
  lines.push("========================================");

  return lines.join("\n");
}
