import { categoryMeta, sortByCategoryOrder } from "@/features/ats-checker/categories";
import type { AtsFullReport } from "@/features/ats-checker/types";

/**
 * Renders the report as plain text for the clipboard. People work on their resume in a
 * different window than the one holding the report, so the fixes need to travel - and a
 * screenshot of a scrolling page does not. Kept deliberately paste-friendly: no box drawing,
 * no colour, nothing that survives badly in a text editor or a notes app.
 */
export function reportToPlainText(report: AtsFullReport, siteUrl: string): string {
  const lines: string[] = [
    "VeriWorkly ATS report",
    "",
    `ATS readiness: ${report.readinessScore}/100`,
    report.jobMatchScore !== null
      ? `Job match: ${report.jobMatchScore}/100`
      : "Job match: not scored (no job description provided)",
    `Checks passed: ${report.checksPassed} of ${report.checksTotal}`,
    `Resume length: ${report.wordCount.toLocaleString()} words`,
    "",
    "AREA BREAKDOWN",
  ];

  for (const entry of sortByCategoryOrder(report.categories)) {
    lines.push(
      `- ${categoryMeta(entry.category).label}: ${entry.score}% (${entry.passed}/${entry.total} checks)`,
    );
  }

  const failed = [...report.failedChecks].sort((a, b) => b.scoreImpact - a.scoreImpact);
  if (failed.length) {
    lines.push("", "FIX THESE FIRST");
    failed.forEach((rule, index) => {
      lines.push(
        `${index + 1}. ${rule.fix}`,
        `   Why: ${rule.evidence}`,
        `   Worth: ${Math.round(rule.scoreImpact)} points`,
      );
    });
  }

  if (report.jobMatchScore !== null) {
    lines.push(
      "",
      "KEYWORDS",
      `Matched: ${report.matchedKeywords.join(", ") || "none"}`,
      `Missing: ${report.missingKeywords.join(", ") || "none"}`,
    );
  }

  if (report.strengths.length) {
    lines.push("", "ALREADY WORKING");
    for (const strength of report.strengths) lines.push(`- ${strength}`);
  }

  lines.push("", `Generated by ${siteUrl}/ats-checker`);
  return lines.join("\n");
}
